### ISSUE TITLE
Don't start

### ISSUE THREAD

**Issue by magic2910** [grimmpp/enocean-device-manager#14]
Installed on Windows 11 with python 3.7

`PS C:\Users\Administrator> .\.venv\Scripts\python.exe -m eo_man
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\.venv\lib\site-packages\eo_man\__main__.py", line 4, in <module>
    from typing import Final
ImportError: cannot import name 'Final' from 'typing' (C:\Program Files\Python37\lib\typing.py)`

What I'm doing wrong?

Btw, thank you for the Eltako Integration :)

**Comment by grimmpp** [comment]
mh, I thought typing is actually preinstalled. Can you try to install it: `.\.venv\Scripts\pip.exe install typing`

**Comment by magic2910** [comment]
Same issue

`PS C:\Users\Administrator> .\.venv\Scripts\python.exe -m eo_man
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\.venv\lib\site-packages\eo_man\__main__.py", line 4, in <module>
    from typing import Final
ImportError: cannot import name 'Final' from 'typing' (C:\Program Files\Python37\lib\typing.py)`

**Comment by grimmpp** [comment]
What python version are you using?

I've tested it again and for me it is working:
```
PS C:\Users\automation> python.exe --version
Python 3.11.3
PS C:\Users\automation> python.exe -m venv .venv
PS C:\Users\automation> .\.venv\Scripts\pip.exe install eo_man
Collecting eo_man
  Using cached eo_man-0.1.11-py3-none-any.whl (864 kB)
Collecting eltako14bus==0.0.46
  Using cached eltako14bus-0.0.46-py3-none-any.whl (46 kB)
Collecting requests==2.31.0
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting enocean==0.60.1
  Using cached enocean-0.60.1-py3-none-any.whl (25 kB)
Collecting pyserial
  Using cached pyserial-3.5-py2.py3-none-any.whl (90 kB)
Collecting pyserial-asyncio
  Using cached pyserial_asyncio-0.6-py3-none-any.whl (7.6 kB)
Collecting aiocoap
  Using cached aiocoap-0.4.7-py3-none-any.whl (208 kB)
Collecting pyyaml
  Using cached PyYAML-6.0.1-cp311-cp311-win_amd64.whl (144 kB)
Collecting termcolor
  Using cached termcolor-2.4.0-py3-none-any.whl (7.7 kB)
Collecting strenum
  Using cached StrEnum-0.4.15-py3-none-any.whl (8.9 kB)
Collecting pillow
  Using cached pillow-10.2.0-cp311-cp311-win_amd64.whl (2.6 MB)
Collecting numpy
  Using cached numpy-1.26.4-cp311-cp311-win_amd64.whl (15.8 MB)
Collecting tkinterhtml
  Using cached tkinterhtml-0.7.zip (930 kB)
  Preparing metadata (setup.py) ... done
Collecting enum-compat>=0.0.2
  Using cached enum_compat-0.0.3-py3-none-any.whl (1.3 kB)
Collecting beautifulsoup4>=4.3.2
  Using cached beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.3.2-cp311-cp311-win_amd64.whl (99 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.6-py3-none-any.whl (61 kB)
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.2.1-py3-none-any.whl (121 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2024.2.2-py3-none-any.whl (163 kB)
Collecting soupsieve>1.2
  Using cached soupsieve-2.5-py3-none-any.whl (36 kB)
Installing collected packages: tkinterhtml, strenum, pyserial, enum-compat, eltako14bus, urllib3, termcolor, soupsieve, pyyaml, pyserial-asyncio, pillow, numpy, idna, charset-normalizer, certifi, aiocoap, requests, beautifulsoup4, enocean, eo_man
  DEPRECATION: tkinterhtml is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for tkinterhtml ... done
Successfully installed aiocoap-0.4.7 beautifulsoup4-4.12.3 certifi-2024.2.2 charset-normalizer-3.3.2 eltako14bus-0.0.46 enocean-0.60.1 enum-compat-0.0.3 eo_man-0.1.11 idna-3.6 numpy-1.26.4 pillow-10.2.0 pyserial-3.5 pyserial-asyncio-0.6 pyyaml-6.0.1 requests-2.31.0 soupsieve-2.5 strenum-0.4.15 termcolor-2.4.0 tkinterhtml-0.7 urllib3-2.2.1

[notice] A new release of pip available: 22.3.1 -> 24.0
[notice] To update, run: C:\Users\automation\.venv\Scripts\python.exe -m pip install --upgrade pip
PS C:\Users\automation> .\.venv\Scripts\python.exe -m eo_man
C:\Users\automation\AppData\Local\Programs\Python\Python311\Lib\html\parser.py:170: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  k = self.parse_starttag(i)
2024-03-02 21:16:52,601 eo_man INFO Start Application eo_man
2024-03-02 21:16:52,741 eo_man INFO Name: eo_man
Version: 0.1.11
Summary: Tool to managed EnOcean Devices and to generate Home Assistant Configuration.
Home-Page: https://github.com/grimmpp/enocean-device-manager
Author: Philipp Grimm
License: MIT License
Requires-Python: >=3.7
Lastest_Available_Version: 0.1.11

2024-03-02 21:16:56,973 root INFO Close Application eo-man
2024-03-02 21:16:56,973 root INFO ========================

PS C:\Users\automation>
```

**Comment by magic2910** [comment]
Now it works, I reinstalled python.
Sorry I have no experience with python.

**Comment by grimmpp** [comment]
No worries and thanks for reporting. Only if I know with what people are struggling I can make it more comfortable to use and actually there should be no reason why you need to be in touch with python for using it :-) Maybe I can find an easier way to install it for future use.
