### ISSUE TITLE
Doen not start on Debian

### ISSUE THREAD

**Issue by jneuhauser** [grimmpp/enocean-device-manager#19]
Tried also with with system site package, like:
```
python3 -m venv --system-site-packages venv
```

```shell
$ python3 -m eo_man
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/mnt/work/dev/enOcean/venv/lib/python3.11/site-packages/eo_man/__main__.py", line 22, in <module>
    from .view.main_panel import MainPanel
  File "/mnt/work/dev/enOcean/venv/lib/python3.11/site-packages/eo_man/view/main_panel.py", line 18, in <module>
    from ..view.menu_presenter import MenuPresenter
  File "/mnt/work/dev/enOcean/venv/lib/python3.11/site-packages/eo_man/view/menu_presenter.py", line 20, in <module>
    from .about_window import AboutWindow
  File "/mnt/work/dev/enOcean/venv/lib/python3.11/site-packages/eo_man/view/about_window.py", line 7, in <module>
    from idlelib.tooltip import Hovertip
ModuleNotFoundError: No module named 'idlelib'
```

I've no clue about why idlelib is missing...

**Comment by grimmpp** [comment]
Thanks for reporting. I initially choose tkinter so that the app is OS-independent so far I found not time to test it on linux and OSX.

**Comment by HotteX** [comment]
As this is still open (even if its old): Its not a bug, merely a missing dependency.

"idlelib" is provided by the package idle-python3* that needs to be installed (like python3-tk and python3-venv).

eodm runs with debian, but cannot see any device to connect to and also cannot load PCT-Export it seems

**Comment by grimmpp** [comment]
Check out https://github.com/grimmpp/enocean-device-manager/blob/main/install_from_officials_on_ubuntu.sh as well, maybe it helps.
