### ISSUE TITLE
Detect serial ports fails on OSX

### ISSUE THREAD

**Issue by benediktarnold** [grimmpp/enocean-device-manager#22]
Hi!
I installed the device manager on OSX (python 3.12) and I'm able to launch it. If I try to detect the serial ports, I get the following error:

```
2024-04-08 17:24:34,959 ERROR root Was not able to detect serial ports.
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/eltako/lib/python3.12/site-packages/eo_man/view/serial_communication_bar.py", line 206, in detect_serial_ports
    self.main.config(cursor="watch")    #set cursor for waiting
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/eltako/lib/python3.12/tkinter/__init__.py", line 1721, in configure
    return self._configure('configure', cnf, kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/eltako/lib/python3.12/tkinter/__init__.py", line 1711, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
RuntimeError: main thread is not in main loop
```
I'm no python expert but from a quick research:
It seems that `detect_serial_ports_command` starts a new thread and this thread calls functions on the GUI. With TK this seems to be forbidden.

I'll try to debug more into it and open a PR if I'm successful finding a solution ;-)

**Comment by grimmpp** [comment]
There seems to be an odd issue with pyserial affecting version 0.1.17 changed it back to a more OS-independent hack in 0.1.18. Unfortunately, I do not have OSX for testing.

**Comment by schiller256** [comment]
The issue still exists in Version 0.1.20

`2024-04-25 11:03:05,938 ERROR root Was not able to detect serial ports. 
Traceback (most recent call last):
  File "/Users/xxxxx/.venv/lib/python3.12/site-packages/eo_man/view/serial_communication_bar.py", line 206, in detect_serial_ports
    self.main.config(cursor="watch")    #set cursor for waiting
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/tkinter/__init__.py", line 1721, in configure
    return self._configure('configure', cnf, kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/tkinter/__init__.py", line 1711, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
RuntimeError: main thread is not in main loop`

**Comment by grimmpp** [comment]
Hello @schiller256,

sorry, I dont have OSX to test with.

**Comment by malthee** [comment]
_I got this to run on OSX by doing some fixes. If anyone also only has MacOS and you want a Home Assistant export you can do the following:_

1) **Clone my fork with macOS fixes** (Checkbox errors, Init errors, Datatable not displayed, Threading issues)

    git clone https://github.com/malthee/enocean-device-manager
    cd enocean-device-manager

2) **Install Python 3.12 via python.org**  
   It already includes Tk 8.6. **Avoid** using the Homebrew Python/Tk; Brew gave me Tk 9+, which broke the UI.

3) **Create a venv with that exact Python and install deps**

    /Library/Frameworks/Python.framework/Versions/3.12/bin/python3 -m venv .venv
    source .venv/bin/activate
    pip install -r requirements.txt

4) **List your USB serial port (macOS uses `/dev/cu.*`)**

    python -m serial.tools.list_ports -v
    **Example result to use later: /dev/cu.usbserial-xxxxxxxx**

5) **Run the application**

    python -m eo_man

6) **In eo_man: enter the Serial Port → Connect** and wait

7) **Press “Scan for devices” and wait for the scan to finish**

8) **Export for Home Assistant**  
   Click the **Home Assistant** button and save the YAML.

---

### Notes
I don't know if this code is ready for a PR, it has some changes that Windows does not need and I did not really check code quality. But for all you MacOS users out there this should at least be helpful to get that initial export.
I also did not test anything more than connecting/scanning, so no sending etc.
