### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by sir-andreas** [grimmpp/enocean-device-manager#34]
Hi,

when I try to connect to my FAM14 via USB cable I do the scan for serial ports. I seems to recognize that, but in the console I get the following error:
```
2024-07-24 08:58:08,579 INFO eltakobus.serial Serial communication started
2024-07-24 08:58:08,591 INFO eltakobus.serial Established serial connection to COM3 - baudrate: 9600
2024-07-24 08:58:08,622 INFO eo_man FAM14 detected on serial port COM3,(baudrate: 9600)
2024-07-24 08:58:08,749 INFO eltakobus.serial Serial communication stopped
```

Nevertheless, I can select COM3 after that in the tool and start the scan, but then the console delivers the following errors and the program hangs after that:
```
2024-07-24 08:58:22,137 INFO eltakobus.serial Serial communication started
2024-07-24 08:58:22,157 INFO eltakobus.serial Established serial connection to COM3 - baudrate: 57600
2024-07-24 08:58:22,188 INFO eo_man Serial connection established. serial port: COM3, baudrate: 57600
2024-07-24 08:58:23,229 ERROR eo_man Failed to load FAM14!!!
2024-07-24 08:58:23,248 ERROR root Failed to load FAM14!!!
Traceback (most recent call last):
  File "C:\Users\RA_2142\.venv\Lib\site-packages\eo_man\controller\serial_controller.py", line 435, in _get_fam14_device_on_bus
    self.current_base_id = await fam14.get_base_id()
                                 ^^^^^^^^^^^^^^^^^
AttributeError: 'BusObject' object has no attribute 'get_base_id'
Exception in thread Thread-6 (run):
Traceback (most recent call last):
  File "C:\Python312\Lib\threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "C:\Python312\Lib\threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\RA_2142\.venv\Lib\site-packages\eo_man\controller\serial_controller.py", line 236, in run
    asyncio.run( self._get_fam14_device_on_bus() )
  File "C:\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\RA_2142\.venv\Lib\site-packages\eo_man\controller\serial_controller.py", line 444, in _get_fam14_device_on_bus
    raise e
  File "C:\Users\RA_2142\.venv\Lib\site-packages\eo_man\controller\serial_controller.py", line 435, in _get_fam14_device_on_bus
    self.current_base_id = await fam14.get_base_id()
                                 ^^^^^^^^^^^^^^^^^
AttributeError: 'BusObject' object has no attribute 'get_base_id'
```

How could that be solved? 

I also checked the connection and the device readout with the PCT14 tool and that worked perfectly. 

Thanks

**Comment by grimmpp** [comment]
Can you try again with the current Version?
