### ISSUE TITLE
Installateion Error Windows

### ISSUE THREAD

**Issue by kmidt** [grimmpp/enocean-device-manager#58]
I became an Error due the Installation : 

PS C:\Users\admin> .\.venv\Scripts\pip.exe install eo_man  --force-reinstall
Collecting eo_man
  Using cached eo_man-0.1.40-py3-none-any.whl.metadata (7.7 kB)
Collecting aiocoap==0.4.7 (from eo_man)
  Using cached aiocoap-0.4.7-py3-none-any.whl.metadata (9.0 kB)
Collecting eltako14bus==0.0.64 (from eo_man)
  Using cached eltako14bus-0.0.64-py3-none-any.whl.metadata (3.2 kB)
Collecting numpy==1.26.3 (from eo_man)
  Using cached numpy-1.26.3.tar.gz (15.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pillow==10.2.0 (from eo_man)
  Using cached pillow-10.2.0.tar.gz (46.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "c:\users\admin\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "c:\users\admin\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "c:\users\admin\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\admin\AppData\Local\Temp\pip-build-env-lvjx8jwu\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\admin\AppData\Local\Temp\pip-build-env-lvjx8jwu\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\admin\AppData\Local\Temp\pip-build-env-lvjx8jwu\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 31, in <module>
        File "<string>", line 28, in get_version
      KeyError: '__version__'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
PS C:\Users\admin>

Whats wrong ?

Greetz ,
Andi

**Comment by C-r-e-d-o** [comment]
I receive the same error

**Comment by baetzmr** [comment]
same here

**Comment by baetzmr** [comment]
downgrading to python 3.12.1 worked for me.  version before was 3.13.1
